# Change these values
owner: 4ht0h10 # Your GitHub organization or username, where this repository lives
repo: upptime  # The name of this repository

sites:
  - name: ELOFICASH Preproducción
    url: https://preprosegur.covline.es/ELOFICASH_PROSEGUR
    icon: http://www.google.com/s2/favicons?domain=covline.es
    __dangerous__body_down_if_text_missing: 'PREPRODUCCIÓN PROSEGUR'
    maxResponseTime: 10000
    assignees:
      - desafecto
  - name: (DEV4) Oracle ERP Cloud
    url: https://emgy-dev4.login.em4.oraclecloud.com/oam/server/obrareq.cgi?encquery%3DlXMni1Qvxm5oWpsjWDFpO4esM%2BXUw720eyQBwFvIRBf3VGg%2FNWXD8kCH%2Fts%2F2pF1Mt42ygKKahxwnncQdzV6oSScEr6GBPDBYBPXclNkqD%2BPb7oJZ3mdm2CWdRWx3%2FjrtpiVrQ9KUdIWnXjMisI3jZfvH5PQyTkNyVMAQnOIT4fyshO3wd4NmhZs4sbLYRk93QbaOYXwA0%2BkFOUBhCCMGoDzhnw1w8ZVAyM2X%2B0%2FvoBxvy6LwX%2BuaoTvPyIAdd19%2B6nnsjyH9FRdJuU7Nol1k0%2F%2FUcdkSEzNgFvOdugeSDjDxLaF7fwcARyVnXECeYZnKsejHSMzrEpSXRBqBnvoF5wLe%2F0g4YTrwYF21x6PN83KSn1TLs8hgm4mr1EN7Eo74xDQ%2BeHvRgGKLVij4Z%2F%2FxX93H2VQQ2HpIve2k953%2BRKn2hPZ%2FxIXBRDweSTLNLh78yDxKi3yUcDlPZ0VPMtPw9zsDq5TEszYvVUcL8Omu7cvtl7Ab%2FSME%2B76zzX9HGWgDhu9K4ZlLxl%2FZbgkQ8OGaLvNn7geLrGjHlgvfFXktrxBVW%2FER9X6aKYZ1kcSAt6N4jjP2YLmvRee1zYsL%2BxB7VCHLJnpm1ux9zhiCy1N2UYNgvgmtowDNIOyyoKSyIQzgNpiZUtZq0wHRwyQy6ISM3bEk2IyZFt4YuQy0di0jHZ%2BTu4GBOwIGmtl6n90MPCg4oEqy7hsq2JFAwyJ%2FfA73rD1lrnA371cPW7PaIp0EzWHo3trKcN5L0Ix04WWOuLREHQc4Jd2pu3E60jCX%2FQkykqF0MQyrz4ssnnjst5Fuagvva0Wq%2FjkRTwFNZPoJFtp2szozCBVMNrOgxGENr7zXjM8C0rnL2JbWXZH7hKHOdraX%2B%2F0OnUoWW6P6sv54EJUImMgZaT9e%2FPiZjOiGiEIXx7%2FKZO6UaeMWOzz%2B7hbcwoidwerTI6KRgvu%2FRKbltk6tbV5GvhhDBeu2jtPncs4Mbo2Rjw8bryDUIPeOnnoIi5XAMByxOOOOxZnf17XE7JPBL%2BznBhZZWhxD0ec2tJbqVVdSOnvrFZthDUg66GrSPaou9jFzfzxQoZmfcCDoXXPWTC6whTramx3y%2FG0eFWDFLK9Py1wt74mHg5fottoxm3dDYm3kOqqo1nONq%2BK3Pd50NsX5YimdDb2YKDScFZhs6Iw%2FR9vhVtNcs%2F7yrTSFfKm5yYbFBKVRHa2syxB8GL%2BlAk2R3JVqkjrjSIOFati1lm4Rfzr9sUelstmfEkEV5ZU%2B2x%2BXXT9PkIuxVb%2BfEiNRqvoinzU2TnD5ZSW33o6bgsw1qJ69cRRNIGSY6lZ82SzEw9kyfuEl8hjGMvbb%2F59WmkS8t8K8Qn9FkYOrMlTxICjwVjCKxqQSJWiwTRQU8Bi4EI0HI%2BY2K58FGoRCv%2BueWaYtOtJ6mt4KCA6iYXBDQDm%2FLHdLEong2sTxHpyWbU%2Bo0bxSRTfKqwRCNA446bio9aL3qC6CvTj713jEOhg2qYVE8Den3kO%2BEqw%2F0agy%2BJ2Jd2PHuldXJPY6XXXEPzYr%2BRWghnMz%2FwmbEJYmj9lbREFXmzKcpIFLUj7gaCgk5ouh%2Fkiu2GCeBUDcoST%2BdEGOJDcfXl8x7DmCyAP02hPoMhyMEap7OrK6xgrxjamY8NZBzKFquV%2BTusCy9fSennV%20agentid%3DOraFusionApp_11AG%20ver%3D1%20crmethod%3D2%26cksum%3D60468a85b760abdbd5d764050959596a8a04f172&ECID-Context=1.005qyih99mB1VcE5v7h8iX0002Uw000HOC%3BkXjE
    __dangerous__body_down_if_text_missing: 'Sign In'
    icon: http://www.google.com/s2/favicons?domain=oracle.com
    maxResponseTime: 5000
    assignees:
      - desafecto
  - name: Connect to Oracle Cloud
    url: https://login.em2.oraclecloud.com/oam/server/obrareq.cgi?encquery%3DSarTfgaOuHg9MY%2BHN7J3jxfpapXzdzmWFmTs550vZluCMcdQOQ%2FwdvzXoHFg6JxWZcGlxTeTaxznB7oBW%2FFbzduJHRLMSwhTYjK5g4bXd9Hk0nrxjqYl5yHxTDJGOTCAf0gekwbq0DbbZtfigk2QIfx61vQQDCCydCyJasvZWuMEa5dOyP%2B%2BhqwojGCZWx31KjdQNBqPB6xVP%2FHDDfAm7o5Wd%2Bg7zVpQSABHoP%2FkXXTmxxqrcecAEYqNzolY2dns%2BQC4mLG9N0jgln2dxgmQQM%2Bx4ByDVaEj4cT43G0Qnv%2BZazBThBR%2Bouu9ycMkpjUl%20agentid%3DPlanning_WG%20ver%3D1%20crmethod%3D2%26cksum%3Dd665189fc8fd2eea97ab903ac055731733c6f5d9
    icon: http://www.google.com/s2/favicons?domain=covline.es
    __dangerous__body_down_if_text_missing: 'ORACLE CLOUD'
    maxResponseTime: 10000
    assignees:
      - desafecto

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://upload.wikimedia.org/wikipedia/commons/0/05/Robot_icon.svg
  faviconSvg: https://upload.wikimedia.org/wikipedia/commons/0/05/Robot_icon.svg
  #css: ":root {
  #            --body-background-color: #FFFFCC;
  #            --card-background-color: #FFC300;
  #            --nav-background-color:  #FFC300;
  #       }"
  #themeUrl: https://4ht0h10.github.io/upptime/my-custom-theme.css
  name: Monitorización de servicios
  introTitle: "Dashboard de _Status monitoring_ hecha con **upptime.js**"
  introMessage: Monitoriza el estado de servicios permitiendo asignar automáticamente _incidencias_ y hacerles seguimiento
  navbar:
    - title: Proyecto ERP Cloud
      href: https://prosegur365.sharepoint.com/sites/ERPCloud
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  i18n:
    activeIncidents: Incidentes activos :(
    allSystemsOperational: Todos los sistemas están operativos


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
