# Change these first
owner: 4ht0h10 # Your GitHub organization or username, where this repository lives
repo: upptime  # The name of this repository

sites:
  - name: Oracle ERP Cloud (DEV1)
    url: https://emgy-dev1.fa.em4.oraclecloud.com
  - name: Oracle ERP Cloud (DEV4)
    url: https://emgy-dev4.fa.em4.oraclecloud.com
  - name: [Jira] PRY-ES-ERP Cloud Implantaciones
    url: https://procde.prosegur.com/jira/projects/ECUP/summary
  - name: [Jira] PRY-ES-ERP Cloud
    url: https://procde.prosegur.com/jira/projects/ERPC/summary
  - name: [Jira] PRY-ES-Migración Cutover
    url: https://procde.prosegur.com/jira/projects/MICO/summary

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime Status website
  introTitle: "Ejemplo de página de _Status monitoring_ hecha con **Upptime**"
  introMessage: Monitoriza el estado de servicios permitiendo asignar automáticamente _incidencias_ y hacerles seguimiento
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
